name: 'Sync Novu State'
description: 'This action syncs your state with Novu Cloud.'
author: 'Novu'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'message-circle'
  color: 'white'

# Define your inputs here.
inputs:
  secret-key:
    description: 'Your Novu secret key'
    required: true
  bridge-url:
    description: 'Your Bridge deployment endpoint URL'
    required: true
  api-url:
    description: 'The Novu Cloud API URL'
    required: false
    default: 'https://api.novu.co'

# Define your outputs here.
outputs:
  success:
    description: 'The status of the sync'
  result:
    description: 'The sync result object'
runs:
  using: node20
  main: dist/index.js
